CREATE TABLE MEMBER(
	MEMBER_SEQ NUMBER PRIMARY KEY
	, MEMBER_NAME VARCHAR2(1000) NOT NULL
	, MEMBER_PW VARCHAR2(100) NOT NULL
	, MEMBER_EMAIL VARCHAR2(100) NOT NULL UNIQUE
	, MEMBER_INVAILD NUMBER(1) DEFAULT 0 NOT NULL
	, MEMBER_IMG VARCHAR2(2000) DEFAULT 'default.png'
	, MEMBER_TYPE NUMBER(1) DEFAULT 0
	, MEMBER_REGDATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE MEMBER_SEQ;

CREATE TABLE PLACE(
	PLACE_SEQ NUMBER PRIMARY KEY
	, PLACE_NAME VARCHAR2(500) NOT NULL
	, PLACE_HIRAGANA VARCHAR2(1000) NOT NULL
	, PLACE_AREA VARCHAR2(2) NOT NULL
	, PLACE_TYPE VARCHAR2(2) NOT NULL
	, PLACE_OPENTIME VARCHAR2(10)
	, PLACE_CLOSETIME VARCHAR2(10)
	, PLACE_SPENDTIME VARCHAR2(10)
	, PLACE_LOCATION VARCHAR2(1000)
	, PLACE_DETAIL VARCHAR2(4000)
	, PLACE_IMAGE VARCHAR2(2000)
	, PLACE_COST NUMBER
	, PLACE_HOMEPAGE VARCHAR2(2000)
);

CREATE SEQUENCE PLACE_SEQ;

CREATE TABLE PLACE_TYPE(
	PLACE_TYPE_SEQ NUMBER PRIMARY KEY
	, PLACE_SEQ NUMBER
	, PLACE_TYPE_GENDER NUMBER(1)
	, PLACE_TYPE_ACTIVITY NUMBER(1)
	, PLACE_TYPE_RESTAURANT NUMBER(1)
	, PLACE_TYPE_DRINKING NUMBER(1)
	, PLACE_TYPE_MAJORITY NUMBER(1)
	, PLACE_TYPE_MANIA NUMBER(1)
	, PLACE_TYPE_EXHIBITION NUMBER(1)
	, PLACE_TYPE_LOCATION NUMBER(1)
	, CONSTRAINT PLACE_TYPE_PLACE_FK FOREIGN KEY (PLACE_SEQ) REFERENCES PLACE(PLACE_SEQ) ON DELETE CASCADE
);

CREATE SEQUENCE PLACE_TYPE_SEQ;

CREATE TABLE PLACE_THEME(
	PLACE_THEME_SEQ NUMBER PRIMARY KEY
	, PLACE_SEQ NUMBER
	, PLACE_THEME_FOOD NUMBER(1)
	, PLACE_THEME_SHOPPING NUMBER(1)
	, PLACE_THEME_HISTORY NUMBER(1)
	, PLACE_THEME_COUPLE NUMBER(1)
	, CONSTRAINT PLACE_THEME_PLACE_FK FOREIGN KEY (PLACE_SEQ) REFERENCES PLACE(PLACE_SEQ) ON DELETE CASCADE
);

CREATE SEQUENCE PLACE_THEME_SEQ;

CREATE TABLE PLACE_GRADE(
	PLACE_GRADE_SEQ NUMBER PRIMARY KEY
	, PLACE_SEQ NUMBER
	, MEMBER_SEQ NUMBER
	, PLACE_GRADE_VALUE NUMBER NOT NULL
	, PLACE_GRADE_REGDATE DATE DEFAULT SYSDATE
	, CONSTRAINT PLACE_GRADE_PLACE_FK FOREIGN KEY (PLACE_SEQ) REFERENCES PLACE(PLACE_SEQ) ON DELETE CASCADE
	, CONSTRAINT PLACE_GRADE_MEMBER_FK FOREIGN KEY (MEMBER_SEQ) REFERENCES MEMBER(MEMBER_SEQ)
);

CREATE SEQUENCE PLACE_GRADE_SEQ;

CREATE TABLE PLACE_REVIEW(
	PLACE_REVIEW_SEQ NUMBER PRIMARY KEY
	, PLACE_SEQ NUMBER
	, MEMBER_SEQ NUMBER
	, PLACE_REVIEW_CONTENT VARCHAR2(4000)
	, PLACE_REVIEW_REGDATE DATE DEFAULT SYSDATE
	, CONSTRAINT PLACE_REVIEW_PLACE_FK FOREIGN KEY (PLACE_SEQ) REFERENCES PLACE(PLACE_SEQ) ON DELETE CASCADE
	, CONSTRAINT PLACE_REVIEW_MEMBER_FK FOREIGN KEY (MEMBER_SEQ) REFERENCES MEMBER(MEMBER_SEQ)
);

CREATE SEQUENCE PLACE_REVIEW_SEQ;

CREATE TABLE PLAN(
	PLAN_SEQ NUMBER PRIMARY KEY
	, MEMBER_SEQ NUMBER
	, PLAN_TITLE VARCHAR2(1000)
	, PLAN_PEOPLECOUNT NUMBER
	, PLAN_FROM DATE
	, PLAN_TO DATE
	, PLAN_AREA NUMBER(1)
	, PLAN_STARTLOCATION VARCHAR2(1000)
	, PLAN_IMG VARCHAR2(1000)
	, CONSTRAINT PLAN_MEMBER_FK FOREIGN KEY (MEMBER_SEQ) REFERENCES MEMBER(MEMBER_SEQ)	
);

CREATE SEQUENCE PLAN_SEQ;

CREATE TABLE PLAN_DAY(
	PLAN_DAY_SEQ NUMBER PRIMARY KEY
	, PLAN_SEQ NUMBER
	, PLAN_DAY_DATE DATE NOT NULL
	, CONSTRAINT PLAN_DAY_PLAN_FK FOREIGN KEY (PLAN_SEQ) REFERENCES PLAN(PLAN_SEQ) ON DELETE CASCADE
);

CREATE SEQUENCE PLAN_DAY_SEQ;

CREATE TABLE PLAN_DAY_PLACE(
	PLAN_DAY_PLACE_SEQ NUMBER PRIMARY KEY
	, PLAN_DAY_SEQ NUMBER
	, PLACE_SEQ NUMBER
	, CONSTRAINT PLAN_DAY_PLACE_PLAN_DAY_FK FOREIGN KEY (PLAN_DAY_SEQ) REFERENCES PLAN_DAY(PLAN_DAY_SEQ) ON DELETE CASCADE
	, CONSTRAINT PLAN_DAY_PLACE_PLACE_FK FOREIGN KEY (PLACE_SEQ) REFERENCES PLACE(PLACE_SEQ)
);

CREATE SEQUENCE PLAN_DAY_PLACE_SEQ;

CREATE TABLE BOARD(
	BOARD_SEQ NUMBER PRIMARY KEY
	, MEMBER_SEQ NUMBER
	, PLAN_SEQ NUMBER
	, BOARD_CONTENT VARCHAR2(4000)
	, BOARD_HITCOUNT NUMBER DEFAULT 0
	, BOARD_REGDATE DATE DEFAULT SYSDATE
	, CONSTRAINT BOARD_MEMBER_FK FOREIGN KEY (MEMBER_SEQ) REFERENCES MEMBER(MEMBER_SEQ)	
	, CONSTRAINT BOARD_PLAN_FK FOREIGN KEY (PLAN_SEQ) REFERENCES PLAN(PLAN_SEQ) ON DELETE CASCADE
);

CREATE SEQUENCE BOARD_SEQ;

CREATE TABLE BOARD_COMMENT(
	BOARD_COMMENT_SEQ NUMBER PRIMARY KEY
	, BOARD_SEQ NUMBER
	, MEMBER_SEQ NUMBER
	, BOARD_COMMENT_CONTENT VARCHAR2(4000)
	, BOARD_COMMENT_REGDATE DATE DEFAULT SYSDATE
	, CONSTRAINT BOARD_COMMENT_BOARD_FK FOREIGN KEY (BOARD_SEQ) REFERENCES BOARD(BOARD_SEQ) ON DELETE CASCADE
	, CONSTRAINT BOARD_COMMENT_MEMBER_FK FOREIGN KEY (MEMBER_SEQ) REFERENCES MEMBER(MEMBER_SEQ)	
);

CREATE SEQUENCE BOARD_COMMENT_SEQ;

CREATE TABLE FAVORITE(
	FAVORITE_SEQ NUMBER PRIMARY KEY
	, BOARD_SEQ NUMBER
	, MEMBER_SEQ NUMBER
	, FAVORITE_REGDATE DATE DEFAULT SYSDATE
	, CONSTRAINT FAVORITE_BOARD_FK FOREIGN KEY (BOARD_SEQ) REFERENCES BOARD(BOARD_SEQ) ON DELETE CASCADE
	, CONSTRAINT FAVORITE_MEMBER_FK FOREIGN KEY (MEMBER_SEQ) REFERENCES MEMBER(MEMBER_SEQ)
);

CREATE SEQUENCE FAVORITE_SEQ;







DROP TABLE FAVORITE;
DROP TABLE BOARD_COMMENT;
DROP TABLE BOARD;
DROP TABLE PLAN_DAY_PLACE;
DROP TABLE PLAN_DAY;
DROP TABLE PLAN;
DROP TABLE PLACE_REVIEW;
DROP TABLE PLACE_GRADE;
DROP TABLE PLACE_THEME;
DROP TABLE PLACE_TYPE;
DROP TABLE PLACE;
DROP TABLE MEMBER;

DROP SEQUENCE FAVORITE_SEQ;
DROP SEQUENCE BOARD_COMMENT_SEQ;
DROP SEQUENCE BOARD_SEQ;
DROP SEQUENCE PLAN_DAY_PLACE_SEQ;
DROP SEQUENCE PLAN_DAY_SEQ;
DROP SEQUENCE PLAN_SEQ;
DROP SEQUENCE PLACE_REVIEW_SEQ;
DROP SEQUENCE PLACE_GRADE_SEQ;
DROP SEQUENCE PLACE_THEME_SEQ;
DROP SEQUENCE PLACE_TYPE_SEQ;
DROP SEQUENCE PLACE_SEQ;
DROP SEQUENCE MEMBER_SEQ;